export const CENTURIES_PER_BATTALION = 10
export const TROOPS_PER_CENTURY = 100
export const MAX_TROOPS_PER_BATTALION = CENTURIES_PER_BATTALION * TROOPS_PER_CENTURY
export const MAX_BATTALIONS_PER_CORPS = 10
export const UNDERSTRENGTH_MARCH_THRESHOLD = 500
